import os

DB_NAME = 'zeus'
EXP_COLLECTION_NAME = 'experiments'
WORKER_COLLECTION_NAME = 'workers'

OLIMP_IP = os.environ['OLIMP_IP']
PUBLIC_OLIMP_IP = os.environ['PUBLIC_OLIMP_IP']

MONGODB_HOST = OLIMP_IP
MONGODB_PORT = 27017

BOKEH_HOST = OLIMP_IP
BOKEH_PORT = 5006

PUBLIC_BOKEH_HOST = PUBLIC_OLIMP_IP
PUBLIC_BOKEH_PORT = 5006


STORAGE_PATH = '/var/storage'


